name: CI/CD Production Env

on:
  push:
    branches: ["prod"]
  pull_request:
    branches: ["prod"]

env:
  ENVIRONMENT: production
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_CONTAINER_NAME: account-center

jobs:
  build:
    name: Test & Build for Production
    runs-on: ["ubuntu-latest"]
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Create .env file
        run: |
          echo "VITE_ENV=${{ vars.ENV }}" >> .env
          echo "VITE_BASE_URL=${{ vars.BASE_URL }}" >> .env
          echo "VITE_ACCESS_EXPIRE=${{ vars.ACCESS_EXPIRE }}" >> .env
          echo "VITE_REFRESH_EXPIRE=${{ vars.REFRESH_EXPIRE }}" >> .env
          echo "VITE_APP_URL=${{ vars.APP_URL }}" >> .env
          echo "VITE_BASE_PATH=${{ vars.BASE_PATH }}" >> .env
          echo "VITE_STRIPE_PUBLIC_KEY=${{ vars.STRIPE_PUBLIC_KEY }}" >> .env
          echo "VITE_DAPP_ENV=${{ vars.DAPP_ENV }}" >> .env
          echo "VITE_WORK_URL=${{ vars.WORK_URL }}" >> .env
          echo "VITE_FUND_URL=${{ vars.FUND_URL }}" >> .env
          echo "VITE_VERIFY_URL=${{ vars.VERIFY_URL }}" >> .env

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy on Production
    needs: [build]
    runs-on: ["socious-runner"]
    if: github.event_name != 'pull_request'
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Docker run
        run: |
          docker pull ${{ steps.meta.outputs.tags }}
          docker ps -qa --filter "name=${{ env.DOCKER_CONTAINER_NAME }}" | grep -q . && docker stop ${{ env.DOCKER_CONTAINER_NAME }} && docker rm -fv ${{ env.DOCKER_CONTAINER_NAME }}
          docker run -d --restart always -p 3000:3000 -h ${{ env.DOCKER_CONTAINER_NAME }} --name ${{ env.DOCKER_CONTAINER_NAME }} ${{ steps.meta.outputs.tags }}
